### ISSUE TITLE
Check what content from the onboard wiki can go to TSH website (e.g., autofilling values appendix)

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/onboard#1]

**Comment by hannesdatta** [comment]
- [ ] mothballing
- [ ] git workflow
- [ ] auto-filling values
- [ ] others...?

plus..
- [ ] do a last check for material that can still be made available on TSH.

**Comment by Tomeulnv** [comment]
The only thing that might be left (if not mistaken) is the [data](https://github.com/tilburgsciencehub/onboarding/wiki/Data) part, but I am unsure whether there is much to add. There seems to be a lot of the content already on the website, e.g.:

- [Download data programatically](https://tilburgsciencehub.com/building-blocks/store-and-document-your-data/store-data/download-data/)
- [Documentation](https://tilburgsciencehub.com/building-blocks/store-and-document-your-data/document-data/documenting-new-data/)
- The storage part is similar to this [page](https://tilburgsciencehub.com/building-blocks/configure-your-computer/infrastructure-choice/surf-research-drive/)

@hannesdatta do you think there is something still worth adding there that is missing?

**Comment by hannesdatta** [comment]
Hi Tomeu,
Data will be integrated w/ TSH eventually, I'll take care of it in github.com/tilburgsciencehub/website/issues/272.

Please retire the appendix sections (remove them, so we do not have duplicates in the onboarding wiki). Add references to their shortlinks on TSH where appropriate. THanks!

**Comment by Tomeulnv** [comment]
Hi Hannes,

I have done so for the ones for which the instruction seems much more clear to me (e.g. coding style guides, mothball). However, there are a few appendices that I don't feel very sure on how to deal with them:

- Appendices that are not in the TSH website but are specific to working for Tilburg Uni (IT support, Blade or preparing for the weekly meetings, technical maintenance, Papers). Should they still be kept in the appendices (they are not duplicated in the wiki)?
- The C coding guideline, wasn't added it to TSH because we thought (with Andrea) it might not be that useful for our audience, should I add it to the website or just remove it from the wiki?
- Pages like Workflow, Releases which are not in the appendices but are on the TSH website, should the content be removed from the wiki and just reference to website?

Thank you

**Comment by Tomeulnv** [comment]
[Done ](https://github.com/tilburgsciencehub/onboarding/wiki), removed appendices that were duplicated and are now referenced. [Releases](https://github.com/tilburgsciencehub/onboarding/wiki/Releases) and the [workflow](https://github.com/tilburgsciencehub/onboarding/wiki/Workflow) pages now only reference to TSH website page.
